import numpy as np
import matplotlib.pyplot as plt


plt.figure(figsize=(17,17))
plt.subplot(221)
fichier= np.loadtxt('homogene_m_1.out')
fichier2= np.loadtxt('homogene_m_2.out')
fichier3= np.loadtxt('homogene_m_3.out')
fichier4= np.loadtxt('homogene_m_4.out')
fichier5= np.loadtxt('homogene_m_5.out')


plt.xlabel('Facteur d\'échelle')
plt.ylabel('Densité d\'énergie des différentes espèces')
plt.plot(fichier[:,1],fichier[:,5], label='Matière')
plt.plot(fichier[:,1],fichier[:,4], label='Radiation')
plt.title(r'$\sigma = {sig}. d\sigma/dt = {dsig}. Q={Q} $' .format(sig="%.2e"%fichier[0,2], dsig="%.1e"%fichier[0,3],Q="%.1e"%fichier[0,5]))
plt.plot(fichier4[:,1],fichier4[:,6], label=r'$m= {}$' .format("%.1e"%fichier4[0,4]))
plt.plot(fichier3[:,1],fichier3[:,6], label=r'$m= {}$' .format("%.1e"%fichier3[0,4]))
plt.plot(fichier[:,1],fichier[:,6], label=r'$m= {}$' .format("%.1e"%fichier[0,4]))
plt.plot(fichier2[:,1],fichier2[:,6], label=r'$m= {}$' .format("%.1e"%fichier2[0,4]))
plt.plot(fichier5[:,1],fichier5[:,6], label=r'$m= {}$' .format("%.1e"%fichier5[0,4]))
plt.yscale('log')
plt.xscale('log')
plt.legend(loc='lower left')

plt.subplot(222)
fichier= np.loadtxt('homogene_Q_1.out')
fichier2= np.loadtxt('homogene_Q_2.out')
fichier3= np.loadtxt('homogene_Q_3.out')
fichier4= np.loadtxt('homogene_Q_4.out')

plt.xlabel('Facteur d\'échelle')
plt.ylabel('Densité d\'énergie des différentes espèces')
plt.plot(fichier[:,1],fichier[:,5], label='Matière')
plt.plot(fichier[:,1],fichier[:,4], label='Radiation')
plt.title(r'$m = {m}. \sigma = {sig}. d\sigma/dt={dsig} $' .format(m="%.2e"%fichier[0,4], sig="%.1e"%fichier[0,2],dsig="%.1e"%fichier[0,3]))
plt.plot(fichier3[:,1],fichier3[:,6], label=r'$Q= {}$' .format("%.1e"%fichier3[0,5]))
plt.plot(fichier4[:,1],fichier4[:,6], label=r'$Q= {}$' .format("%.1e"%fichier4[0,5]))
plt.plot(fichier2[:,1],fichier2[:,6], label=r'$Q= {}$' .format("%.1e"%fichier2[0,5]))
plt.plot(fichier[:,1],fichier[:,6], label=r'$Q= {}$' .format("%.1e"%fichier[0,5]))
plt.yscale('log')
plt.xscale('log')
plt.legend(loc='lower left')

plt.subplot(223)
fichier= np.loadtxt('homogene_sigma_1.out')
fichier2= np.loadtxt('homogene_sigma_2.out')
fichier3= np.loadtxt('homogene_sigma_3.out')
fichier4= np.loadtxt('homogene_sigma_4.out')
fichier5= np.loadtxt('homogene_sigma_5.out')

plt.xlabel('Facteur d\'échelle')
plt.ylabel('Densité d\'énergie des différentes espèces')
plt.plot(fichier[:,1],fichier[:,5], label='Matière')
plt.plot(fichier[:,1],fichier[:,4], label='Radiation')
plt.title(r'$m = {m}. d\sigma/dt = {dsig}. Q={Q} $' .format(m="%.2e"%fichier[0,4], dsig="%.1e"%fichier[0,3],Q="%.1e"%fichier[0,5]))
plt.plot(fichier5[:,1],fichier5[:,6], label=r'$\sigma= {}$' .format("%.1e"%fichier5[0,2]))
plt.plot(fichier4[:,1],fichier4[:,6], label=r'$\sigma= {}$' .format("%.1e"%fichier4[0,2]))
plt.plot(fichier3[:,1],fichier3[:,6], label=r'$\sigma= {}$' .format("%.1e"%fichier3[0,2]))
plt.plot(fichier[:,1],fichier[:,6], label=r'$\sigma= {}$' .format("%.1e"%fichier[0,2]))
plt.plot(fichier2[:,1],fichier2[:,6], label=r'$\sigma= {}$' .format("%.1e"%fichier2[0,2]))
plt.yscale('log')
plt.xscale('log')
plt.legend(loc='lower left')

plt.subplot(224)
fichier= np.loadtxt('homogene_dsigma_1.out')
fichier2= np.loadtxt('homogene_dsigma_2.out')
fichier3= np.loadtxt('homogene_dsigma_3.out')
fichier4= np.loadtxt('homogene_dsigma_4.out')
fichier5= np.loadtxt('homogene_dsigma_5.out')

plt.xlabel('Facteur d\'échelle')
plt.ylabel('Densité d\'énergie des différentes espèces')
plt.plot(fichier[:,1],fichier[:,5], label='Matière')
plt.plot(fichier[:,1],fichier[:,4], label='Radiation')
plt.title(r'$m = {m}. \sigma = {sig}. Q={Q} $' .format(m="%.2e"%fichier[0,4], sig="%.1e"%fichier[0,2],Q="%.1e"%fichier[0,5]))
plt.plot(fichier4[:,1],fichier4[:,6], label=r'$d \sigma /dt= {}$' .format("%.1e"%fichier4[0,3]))
plt.plot(fichier5[:,1],fichier5[:,6], label=r'$d \sigma /dt= {}$' .format("%.1e"%fichier5[0,3]))
plt.plot(fichier3[:,1],fichier3[:,6], label=r'$d \sigma /dt= {}$' .format("%.1e"%fichier3[0,3]))
plt.plot(fichier[:,1],fichier[:,6], label=r'$d \sigma /dt= {}$' .format("%.1e"%fichier[0,3]))
plt.plot(fichier2[:,1],fichier2[:,6], label=r'$d \sigma /dt= {}$' .format("%.1e"%fichier2[0,3]))
plt.yscale('log')
plt.xscale('log')
plt.legend(loc='lower left')

plt.show()
